server {
  listen 80;

  # UI root (simple message)
  location / {
    root /usr/share/nginx/html;
    index index.html;
  }

  # Architecture endpoint
  location  /api/arch {
    default_type application/json;
    return 200 '{"arch":"nanoservices-kubernetes"}';
  }

  # Ping endpoint
  location  /api/ping {
    default_type application/json;
    return 200 '{"ok":true}';
  }

  # Checkout route → forward to checkout service
  location /api/checkout {
    rewrite ^/api/(.*) /$1 break;

    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    # IMPORTANT (for later tracing)
    proxy_set_header X-Request-Id $http_x_request_id;

    proxy_pass http://checkout-svc;
  }
}